export type Product = {
  id: string;
  name: string;
  slug: string;
  origin: string;
  region: string | null;
  producer: string | null;
  product_type: "single-origin" | "blend" | "decaf";
  variety: string | null;
  process: string | null;
  roast_level: string | null;
  tasting_notes: string | null;
  description: string | null;
  roasted_date: string | null;
  price_150g: number;
  price_400g: number;
  price_400g_original: number | null;
  stock_quantity: number;
  active: boolean;
  featured: boolean;
  todays_roast: boolean;
  discovery_tags: string[];
  display_order: number;
  image_url: string | null;
  primary_image_url?: string | null;
  thumbnail_url?: string | null;
  created_at?: string;
  korean_name?: string | null;
  subtitle?: string | null;
  short_description?: string | null;
  category?: ProductCategory | null;
  status?: "draft" | "active" | "sold-out" | "hidden";
  sale_price?: number | null;
  gallery_images?: string[];
  washing_station?: string | null;
  altitude?: string | null;
  harvest?: string | null;
  grade?: string | null;
  acidity?: number | null;
  sweetness?: number | null;
  body?: number | null;
  about?: string | null;
  why_we_chose_it?: string | null;
  roaster_note?: string | null;
  recommended_brewing_methods?: string[];
  brewing_dose?: string | null;
  brewing_water?: string | null;
  brewing_temperature?: string | null;
  brewing_grind?: string | null;
  brewing_time?: string | null;
  use_default_recipe?: boolean;
  variants?: ProductVariant[];
};

export type ProductCategory = "comfortable" | "bright" | "decaf" | "blend" | "special";
export type Grind = "Whole Bean" | "Espresso" | "Moka Pot" | "Pour Over" | "Coffee Maker" | "French Press" | "Filter" | "Other";
export type Weight = string;
export type ProductVariant = { id: string; size: string; grindType: Grind; price: number; salePrice?: number | null; sku?: string; stock: number; available: boolean };
export type CartItem = { product: Product; variantId?: string; weight: Weight; grind: Grind; quantity: number; unitPrice: number };
export type OrderItem = { id: string; order_id: string; product_name: string; weight: string; grind: string; quantity: number; unit_price: number; subtotal: number };
export type Order = { id: string; order_number: string; customer_name: string; email: string; phone?: string; fulfillment_type: "delivery" | "pickup"; total: number; payment_status: string; order_status: string; created_at: string; order_items?: OrderItem[] };
