"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Product, ProductVariant } from "@/types";
import { SHOP_TAGS } from "@/lib/shop-tags";
import { productVariants } from "@/lib/products";
import { PRODUCT_SIZES } from "@/lib/product-contract";
import { ImageUpload } from "./ImageUpload";

const fields = ["name","korean_name","subtitle","slug","short_description","product_type","category","status","origin","region","producer","washing_station","variety","process","altitude","harvest","grade","roast_level","tasting_notes","description","about","why_we_chose_it","roaster_note","display_order","image_url","brewing_dose","brewing_water","brewing_temperature","brewing_grind","brewing_time"] as const;
const emptyVariant = (size: ProductVariant["size"]): ProductVariant => ({ id: crypto.randomUUID(), size, price: size === "400g" ? 44000 : 19000, salePrice: size === "400g" ? 29000 : 13000, sku: "", stock: 0, available: true });
const newProductVariants = () => PRODUCT_SIZES.map(size => emptyVariant(size));
export function AdminProductForm({ product }: { product?: Product }) {
 const router=useRouter(); const [form,setForm]=useState<Record<string, unknown>>(()=>({...Object.fromEntries(fields.map(k=>[k,product?.[k as keyof Product]??""])),product_type:product?.product_type??"single-origin",category:product?.category??"comfortable",status:product?.status??"draft",display_order:product?.display_order??0,featured:product?.featured??false,todays_roast:product?.todays_roast??false,use_default_recipe:product?.use_default_recipe??true,acidity:product?.acidity??3,sweetness:product?.sweetness??3,body:product?.body??3,discovery_tags:product?.discovery_tags??[],gallery_images:product?.gallery_images??[],recommended_brewing_methods:product?.recommended_brewing_methods??[],gallery_images_text:(product?.gallery_images??[]).join("\n"),variants:product?productVariants(product):newProductVariants()}));
 const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const change=(key:string,value:unknown)=>setForm(v=>({...v,[key]:value}));
 const input=(key:string,label:string,type="text")=><label className="admin-field">{label}<input type={type} value={String(form[key]??"")} onChange={e=>change(key,type==="number"?Number(e.target.value):e.target.value)}/></label>;
 const area=(key:string,label:string)=><label className="admin-field admin-field-wide">{label}<textarea value={String(form[key]??"")} onChange={e=>change(key,e.target.value)}/></label>;
 const selectedTags=form.discovery_tags as string[]; const toggleShopTag=(tag:string)=>change("discovery_tags",selectedTags.includes(tag)?selectedTags.filter(value=>value!==tag):[...selectedTags,tag]);
 const variants=form.variants as ProductVariant[]; const setVariant=(i:number,key:keyof ProductVariant,value:unknown)=>change("variants",variants.map((v,index)=>index===i?{...v,[key]:value}:v));
 const setSizePrice=(size:string,key:"price"|"salePrice",value:number)=>change("variants",variants.map(v=>v.size===size?{...v,[key]:value}:v));
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");const payload={...form,discovery_tags:form.discovery_tags as string[],gallery_images:String(form.gallery_images_text || "").split("\n").map(value => value.trim()).filter(Boolean).length ? String(form.gallery_images_text).split("\n").map(value => value.trim()).filter(Boolean) : (form.gallery_images as string[]).filter(Boolean)};try{const response=await fetch("/api/admin/products",{method:product?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(product?{id:product.id,...payload}:payload)});const result=await response.json();if(!response.ok){setMessage(result.error||"Could not save");return;}router.push("/admin/products");router.refresh();}catch{setMessage("Could not save product.");}finally{setSaving(false)}}
 return <form className="admin-product-form" onSubmit={save}>
  {product&&<div className="admin-preview"><Link href={`/shop/${product.slug}?preview=1`} target="_blank">PREVIEW PRODUCT ↗</Link></div>}
  <section className="admin-panel"><p className="eyebrow">A · Basic information</p><h2>Identity & visibility</h2><div className="admin-form-grid">{input("name","Product Name")}{input("korean_name","Korean Name")}{input("subtitle","Subtitle")}{input("slug","Slug")}{area("short_description","Short Description")}<label className="admin-field">Product Type<select value={String(form.product_type)} onChange={e=>change("product_type",e.target.value)}><option value="single-origin">Single Origin</option><option value="blend">Blend</option><option value="decaf">Decaf</option></select></label><label className="admin-field">Category<select value={String(form.category)} onChange={e=>change("category",e.target.value)}><option value="comfortable">Comfortable / Nutty</option><option value="bright">Bright / Floral</option><option value="decaf">Decaf</option><option value="blend">Blend</option><option value="special">Special</option></select></label><label className="admin-field">Status<select value={String(form.status||"active")} onChange={e=>setForm(current=>({...current,status:e.target.value,...(e.target.value!=="active"?{todays_roast:false}:{})}))}><option value="draft">Draft</option><option value="active">Active</option><option value="sold-out">Sold Out</option><option value="hidden">Hidden</option></select></label>{input("display_order","Display Order","number")}</div><div className="admin-toggle-row"><label><input type="checkbox" checked={Boolean(form.featured)} onChange={e=>change("featured",e.target.checked)}/><span><strong>Featured</strong></span></label><label><input type="checkbox" checked={Boolean(form.todays_roast)} disabled={form.status!=="active"} onChange={e=>change("todays_roast",e.target.checked)}/><span><strong>Today's Coffee</strong></span></label></div></section>
  <section className="admin-panel"><p className="eyebrow">SHOP TAG</p><h2>Shop filters</h2><p className="admin-panel-help">하나의 상품에 여러 태그를 선택할 수 있습니다.</p><div className="admin-tag-picker">{SHOP_TAGS.map(tag=><button type="button" key={tag} aria-pressed={selectedTags.includes(tag)} onClick={()=>toggleShopTag(tag)}><span className="admin-tag-check" aria-hidden="true">{selectedTags.includes(tag)?"✓":""}</span><span><strong>{tag}</strong><small>SHOP 필터에 표시</small></span></button>)}</div></section>
  <section className="admin-panel"><p className="eyebrow">B · Price & inventory</p><h2>Size inventory</h2><p className="admin-panel-help">재고는 용량별로 관리합니다. Whole Bean / Filter / Espresso는 주문 시 선택하는 분쇄 옵션이며 재고를 나누지 않습니다.</p><div className="variant-editor size-inventory-editor">{PRODUCT_SIZES.map(size=>{const i=variants.findIndex(v=>v.size===size);const v=variants[i];if(!v)return null;return <div className="variant-row" key={v.id}><strong>{size}</strong><label>정상가격<input min="1" type="number" value={v.price} onChange={e=>setSizePrice(size,"price",Number(e.target.value))}/></label><label>가격<input min="1" type="number" value={v.salePrice??v.price} onChange={e=>setSizePrice(size,"salePrice",Number(e.target.value))}/></label><label>재고<input min="0" type="number" value={v.stock} onChange={e=>setVariant(i,"stock",Number(e.target.value))}/></label><label>판매 가능<input type="checkbox" checked={v.available} onChange={e=>setVariant(i,"available",e.target.checked)}/></label></div>})}</div></section>
  <section className="admin-panel"><p className="eyebrow">C · Coffee information</p><div className="admin-form-grid">{input("origin","Country")}{input("region","Region")}{input("producer","Farm / Producer")}{input("washing_station","Washing Station")}{input("variety","Variety")}{input("process","Processing")}{input("altitude","Altitude")}{input("harvest","Harvest")}{input("grade","Grade")}</div></section>
  <section className="admin-panel"><p className="eyebrow">D · Taste profile</p><div className="admin-form-grid">{area("tasting_notes","Tasting Notes (comma separated)")}{["acidity","sweetness","body"].map(key=><label className="admin-field" key={key}>{key} · {String(form[key])}<input type="range" min="1" max="5" value={Number(form[key])} onChange={e=>change(key,Number(e.target.value))}/></label>)}{input("roast_level","Roast Level")}</div></section>
  <section className="admin-panel"><p className="eyebrow">E · Story / detail</p><div className="admin-form-grid">{area("about","About This Coffee")}{area("why_we_chose_it","Why We Chose It")}{area("roaster_note","Roaster's Note")}</div></section>
  <section className="admin-panel"><p className="eyebrow">F · Brewing guide</p><label className="admin-checkbox"><input type="checkbox" checked={Boolean(form.use_default_recipe)} onChange={e=>change("use_default_recipe",e.target.checked)}/> Use Default Casa di Stefano Recipe</label><div className="admin-form-grid">{input("brewing_dose","Coffee Dose")}{input("brewing_water","Water")}{input("brewing_temperature","Temperature")}{input("brewing_grind","Grind")}{input("brewing_time","Brew Time")}</div></section>
  <section className="admin-panel"><p className="eyebrow">G · Product images</p><ImageUpload onUploaded={url=>change("image_url",url)}/><div className="admin-form-grid">{input("image_url","Primary Image URL")}{area("gallery_images_text","Gallery image URLs (one per line)")}</div></section>
  {message&&<p role="alert" className="admin-form-error">{message}</p>}<div className="admin-form-submit"><button className="admin-primary-button" disabled={saving}>{saving?"Saving…":"Save product"}</button></div>
 </form>;
}
