"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
const weekdays = [[1,"월"],[2,"화"],[3,"수"],[4,"목"],[5,"금"],[6,"토"],[0,"일"]] as const;
type Props = { settings: { free_shipping_threshold:number; standard_shipping_fee:number; local_delivery_enabled:boolean; local_delivery_days:number[]; local_delivery_message:string }; zones: {id:string;name:string;zone_type:string;zone_value:string;enabled:boolean}[] };
export default function DeliverySettingsForm({ settings, zones }: Props) {
 const router=useRouter(); const [form,setForm]=useState(settings); const [zone,setZone]=useState({name:"",zoneType:"district",zoneValue:""}); const [message,setMessage]=useState("");
 async function send(body: object){setMessage("");const response=await fetch("/api/admin/delivery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){setMessage(data.error);return false}router.refresh();setMessage("저장되었습니다.");return true}
 return <div className="delivery-admin"><section className="admin-panel"><p className="eyebrow">STANDARD SHIPPING</p><div className="admin-form-grid"><label>무료배송 기준<input type="number" value={form.free_shipping_threshold} onChange={e=>setForm({...form,free_shipping_threshold:Number(e.target.value)})}/></label><label>기본 배송비<input type="number" value={form.standard_shipping_fee} onChange={e=>setForm({...form,standard_shipping_fee:Number(e.target.value)})}/></label></div><p className="eyebrow admin-form-heading">CASA LOCAL DELIVERY</p><label className="admin-check"><input type="checkbox" checked={form.local_delivery_enabled} onChange={e=>setForm({...form,local_delivery_enabled:e.target.checked})}/> Local Delivery 사용</label><label>안내 문구<textarea value={form.local_delivery_message} onChange={e=>setForm({...form,local_delivery_message:e.target.value})}/></label><div className="admin-days"><span>배송 가능 요일</span>{weekdays.map(([value,label])=><label key={value}><input type="checkbox" checked={form.local_delivery_days.includes(value)} onChange={e=>setForm({...form,local_delivery_days:e.target.checked?[...form.local_delivery_days,value]:form.local_delivery_days.filter(d=>d!==value)})}/>{label}</label>)}</div><button className="admin-primary" onClick={()=>send({action:"settings",freeShippingThreshold:form.free_shipping_threshold,standardShippingFee:form.standard_shipping_fee,localDeliveryEnabled:form.local_delivery_enabled,localDeliveryDays:form.local_delivery_days,localDeliveryMessage:form.local_delivery_message})}>설정 저장</button></section>
 <section className="admin-panel"><p className="eyebrow">LOCAL DELIVERY ZONES</p><p className="admin-muted">행정동이나 우편번호로 구분하기 어려운 주소는 주소 키워드를 추가하세요. 예: 웰빙타운로 또는 웰빙타운로 20</p><div className="zone-add"><input placeholder="지역명" value={zone.name} onChange={e=>setZone({...zone,name:e.target.value})}/><select value={zone.zoneType} onChange={e=>setZone({...zone,zoneType:e.target.value})}><option value="district">행정동/법정동</option><option value="address_keyword">주소 키워드</option><option value="postal_prefix">우편번호 prefix</option><option value="postal_range">우편번호 range</option></select><input placeholder={zone.zoneType === "address_keyword" ? "예: 웰빙타운로 20" : "값 (예: 이의동 / 16500-16599)"} value={zone.zoneValue} onChange={e=>setZone({...zone,zoneValue:e.target.value})}/><button className="admin-secondary" onClick={async()=>{if(await send({action:"zone",...zone}))setZone({name:"",zoneType:"district",zoneValue:""})}}>+ 지역 추가</button></div><div className="zone-table"><div className="zone-row zone-head"><span>지역명</span><span>타입</span><span>값</span><span>상태</span><span /></div>{zones.map(z=><div className="zone-row" key={z.id}><span>{z.name}</span><span>{z.zone_type === "address_keyword" ? "주소 키워드" : z.zone_type}</span><span>{z.zone_value}</span><button onClick={()=>send({action:"toggle",id:z.id,enabled:!z.enabled})}>{z.enabled?"활성":"비활성"}</button><button onClick={()=>send({action:"delete",id:z.id})}>삭제</button></div>)}</div>{message&&<p className="admin-feedback">{message}</p>}</section></div>;
}
