"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { Product } from "@/types";
import { Reveal, StaggerText } from "./Reveal";

const principles = [["01", "ZERO ADDITIVES", "Nothing unnecessary added.", "필요 없는 건 넣지 않습니다."], ["02", "ZERO MASKING", "Never hide the character of the bean.", "콩의 본질을 가리지 않습니다."], ["03", "ZERO GUESSWORK", "Roasting guided by data and experience.", "데이터와 경험으로 로스팅합니다."]];

export function HomeStory({ product }: { product: Product | null }) {
  const [activePrinciple, setActivePrinciple] = useState(0);
  useEffect(() => {
    const sections = [...document.querySelectorAll<HTMLElement>("[data-principle]")];
    const observer = new IntersectionObserver((entries) => { const visible = entries.find((entry) => entry.isIntersecting); if (visible) setActivePrinciple(Number((visible.target as HTMLElement).dataset.principle)); }, { rootMargin: "-35% 0px -45%", threshold: 0 });
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);

  return <main className="home-story">
    <section className="home-scene home-hero"><div className="home-hero-texture" /><div className="home-hero-content"><Reveal variant="fade"><p className="eyebrow text-[var(--paper)]/75">CASA DI STEFANO</p></Reveal><StaggerText className="home-hero-heading"><span className="lang-ko">매일의 커피에<br /><i>조금 더 좋은 순간을.</i></span><span className="lang-en">Good beans.<br /><i>Thoughtfully roasted.</i></span></StaggerText><Reveal delay={180} className="home-hero-subtitle"><p>Coffee Roastery &amp; Tasting Room<br />Suwon, Korea</p></Reveal><Reveal delay={280} className="mt-8 flex flex-wrap gap-4"><Link href="/shop" className="button-primary home-cta">SHOP THE ROASTS <span>↗</span></Link><Link href="/our-story" className="home-cta home-cta-light">OUR STORY <span>↗</span></Link></Reveal></div><p className="home-scroll-cue eyebrow">Scroll to discover <span>↓</span></p></section>
    <section className="home-scene tominiko-story"><div className="story-intro"><Reveal variant="fade"><p className="section-label">TOMINIKO</p><p className="eyebrow mt-3 text-[var(--brown)]">Beans &amp; Coffee</p></Reveal><StaggerText><h2><span className="lang-ko">오늘의<br />커피.</span><span className="lang-en">Today&apos;s<br />Roast.</span></h2></StaggerText><Reveal delay={140}><p className="story-lede lang-ko">한 잔의 인상을 만드는<br />싱글 오리진과 블렌드.</p><p className="story-lede lang-en">A small-batch coffee<br />for the day ahead.</p></Reveal></div><Reveal variant="scale" className="roast-feature"><div className="roast-visual">{product?.image_url ? <img src={product.image_url} alt={product.name} /> : <div className="bag-visual"><span>TOMINIKO</span><strong>COFFEE<br />BEANS</strong><small>ROASTED IN SUWON</small></div>}</div><div className="roast-details"><div><p className="eyebrow text-[var(--muted)]">Today&apos;s roast</p><h3>{product?.name ?? "또미 블렌딩"}</h3><p className="sans text-[11px] uppercase tracking-[.1em] text-[var(--muted)]">{product?.origin ?? "Brazil · Colombia · Ethiopia · Guatemala"}</p></div><div className="roast-notes"><p className="eyebrow">Tasting notes</p><p>{product?.tasting_notes ?? "A warm, balanced cup with a quietly sweet finish."}</p></div><div className="roast-price"><strong>₩{(product?.price_150g ?? 13000).toLocaleString()}</strong><span>150g · Roasted by ZERO DEGREES</span></div><div className="flex flex-wrap gap-5"><Link href={product ? `/shop/${product.slug}` : "/shop"} className="button-primary home-cta">VIEW COFFEE <span>↗</span></Link><Link href="/shop" className="eyebrow border-b border-[var(--ink)] pb-1">BUY <span>↗</span></Link></div></div></Reveal></section>
    <section className="home-scene zero-story"><div className="zero-story-heading"><Reveal variant="fade"><p className="eyebrow text-[#c9c7a8]">ZERO DEGREES · COFFEE ROASTERS</p><h2>A quieter approach<br />to better coffee.</h2><p className="zero-subline">Nothing added.<br />Nothing hidden.</p></Reveal></div><div className="zero-story-stage"><div className="zero-mark">ZERO</div><div className="zero-principle-list">{principles.map(([number, title, en, ko], index) => <article key={number} data-principle={index} className={index === activePrinciple ? "is-active" : ""}><span className="eyebrow">STEP {number}</span><h3>{title}</h3><p>{en}</p><p className="lang-ko">{ko}</p></article>)}</div></div></section>
    <section className="home-scene degrees-story"><div className="degrees-copy"><Reveal variant="fade"><p className="section-label">WHY DEGREES?</p><h2>Craft,<br /><i>measured.</i></h2><p className="degrees-lede">Data helps us understand what happened.<br />Experience helps us decide what happens next.</p></Reveal></div><div className="degrees-words">{["TEMPERATURE", "TIME", "DEVELOPMENT", "RoR"].map((word, index) => <Reveal key={word} delay={index * 80}><span>{word}</span></Reveal>)}</div></section>
    <section className="home-scene tasting-story"><div className="tasting-media"><div className="tasting-placeholder"><span>CASA DI STEFANO</span><small>Tasting Room · Suwon</small></div></div><Reveal className="tasting-copy"><p className="eyebrow">CASA DI STEFANO</p><h2>Tasting Room.</h2><p className="tasting-lede">Coffee is better<br />when it&apos;s shared.</p><p className="eyebrow text-[var(--muted)]">Roasting. Tasting. Coffee. Conversation.</p><Link href="/tasting-room" className="home-cta home-cta-dark">VISIT THE TASTING ROOM <span>↗</span></Link></Reveal></section>
    <section className="home-scene final-brand"><Reveal variant="fade"><p className="eyebrow">CASA DI STEFANO</p><h2>Good Beans.<br /><i>Better Days.</i></h2><p className="eyebrow text-[var(--muted)]">TOMINIKO BEANS &amp; COFFEE<br />Roasted by ZERO DEGREES</p><Link href="/shop" className="home-cta home-cta-dark">SHOP COFFEE <span>↗</span></Link></Reveal></section>
  </main>;
}
