export const pageDefinitions = {
  home: { label: "Home", path: "/", texts: {
    hero_eyebrow: ["Hero eyebrow", "Casa di Stefano · Suwon"], hero_title_ko: ["Hero title (Korean)", "오늘의 기분에 맞는\n좋은 커피 한 잔."], hero_title_en: ["Hero title (English)", "Good coffee,\nfor today."], hero_body_ko: ["Hero body (Korean)", "수원에서 작은 배치로 로스팅하는\nTominiko Beans & Coffee."], hero_body_en: ["Hero body (English)", "Tominiko Beans & Coffee,\nroasted in small batches in Suwon."], brand_title_ko: ["Roastery title (Korean)", "더하지 않고,\n가리지 않는 로스팅."], brand_title_en: ["Roastery title (English)", "Nothing added.\nNothing hidden."], brand_body_ko: ["Roastery text (Korean)", "데이터로 이해하고 경험으로 결정합니다. 커피가 가진 고유한 인상을 조용히 선명하게 만드는 것이 Zero Degrees의 방식입니다."], brand_body_en: ["Roastery text (English)", "We understand with data and decide with experience—making each coffee's character quietly clear."], closing_ko: ["Closing title (Korean)", "천천히 만들고,\n쉽게 고르는 커피."], closing_en: ["Closing title (English)", "Made slowly.\nChosen easily."] }, images: { hero: ["Hero background image", ""] } },
  "our-story": { label: "Our Story", path: "/our-story", texts: { title_ko: ["Title (Korean)", "하나의 집,\n세 가지 역할."], title_en: ["Title (English)", "One house.\nThree ways of seeing coffee."], intro_ko: ["Introduction (Korean)", "이름은 다르지만, 세계관은 하나입니다."], intro_en: ["Introduction (English)", "Different names, one shared point of view."], explanation_ko: ["Explanation (Korean)", "Casa di Stefano는 우리가 머무는 집입니다. Zero Degrees는 그 안에서 커피를 대하는 방식이고, Tominiko는 그 결과를 당신의 하루에 건네는 이름입니다."], explanation_en: ["Explanation (English)", "Casa di Stefano is the house we inhabit. Zero Degrees is how we approach coffee inside it. Tominiko is the name we give to what you bring into your day."], closing: ["Closing statement", "Good beans.\nLess intervention."] }, images: { opening: ["Opening background image", ""] } },
  "tasting-room": { label: "Tasting Room", path: "/tasting-room", texts: { title: ["Hero title", "TASTING\nROOM"], hero_ko: ["Hero line (Korean)", "커피를 맛보고, 이야기를 나누는 곳."], hero_en: ["Hero line (English)", "A place to taste, talk, and take coffee home."], intro_title: ["Introduction title", "Not quite a café.\nSomething more personal."], intro_ko: ["Introduction (Korean)", "Casa di Stefano는 로스터리와 작은 커피 스튜디오가 함께 있는 공간입니다. 로스팅하는 날의 공기, 긴 테이블 위의 잔, 집으로 가져갈 원두가 이곳에 있습니다."], intro_en: ["Introduction (English)", "Casa di Stefano is a roastery and a small coffee studio. The air of a roast day, cups across a long table, and coffee to take home all share the same address."], visit_ko: ["Visit note (Korean)", "현재 테이스팅은 예약제로 준비 중입니다. 곧 이곳에서 일정을 안내해드릴게요."], visit_en: ["Visit note (English)", "Tastings are being prepared by reservation. We will share the next sessions here soon."] }, images: { hero: ["Hero image", "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=2000&q=85"], table: ["Table image", "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1400&q=85"] } },
  "zero-degrees": { label: "Zero Degrees", path: "/zero-degrees", texts: { title: ["Hero title", "COFFEE\nROASTERS"], tagline: ["Hero tagline", "Nothing added.\nNothing hidden."], why_ko: ["Why Zero title (Korean)", "생두가 이미 가진 것을\n가리지 않는 로스팅."], why_en: ["Why Zero title (English)", "A roast that does not\nhide what the bean already has."], why_body_ko: ["Why Zero text (Korean)", "불필요한 것을 더하지 않고, 어떤 개성도 가리지 않으며, 모든 결정을 감에만 맡기지 않는다는 약속입니다."], why_body_en: ["Why Zero text (English)", "It is a promise to add nothing unnecessary, mask no character, and leave no decision to guesswork alone."], craft_title: ["Craft title", "Not automation.\nNot intuition alone."], craft_body: ["Craft text", "Data helps us understand what happened.\nExperience helps us decide what happens next."] }, images: { craft: ["Roaster / craft image", ""] } },
  shop: { label: "Shop", path: "/shop", texts: { title_ko: ["Page title (Korean)", "오늘 준비된 커피"], title_en: ["Page title (English)", "Coffee for today"], subtitle_ko: ["Subtitle (Korean)", "작은 배치로 정성스럽게 로스팅한 커피."], subtitle_en: ["Subtitle (English)", "Coffee, roasted in small batches."], collection_ko: ["Collection title (Korean)", "다른 커피"], collection_en: ["Collection title (English)", "Other coffees"] }, images: {} },
} as const;

export type PageSlug = keyof typeof pageDefinitions;
export type TextSetting = { value: string; font: "serif" | "sans" | "display"; size: string };
export type PageSettings = { texts: Record<string, TextSetting>; images: Record<string, string> };

export function defaultPageSettings(slug: PageSlug): PageSettings {
  const definition = pageDefinitions[slug];
  return { texts: Object.fromEntries(Object.entries(definition.texts).map(([key, entry]) => [key, { value: entry[1], font: "serif", size: "" }])), images: Object.fromEntries(Object.entries(definition.images).map(([key, entry]) => [key, entry[1]])) };
}

